# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "tact.moe"
languageCode = "en-us"
baseURL = "https://tact.moe/"
copyright = "© tactidact {year}"

[author]
    name = "tactidact"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2006-01-02 — 15:04 -0700"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/tactidact"
  github = "https://github.com/tactidact"
  letterboxd = "https://letterboxd.com/tactidact/"
  anilist = "https://anilist.co/user/tact/"
  # email = "mailto:<your email>"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Letterboxd", "AniList"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the blog permalink format
[permalinks]
  blog = "/:year/:month/:day/:filename/"

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = 20



